import type { OtpPattern } from '../../types/extraction.types';

export const OTP_PATTERN_DATABASE: OtpPattern[] = [
  // Standard numeric patterns
  {
    pattern: /\b\d{4}\b/g,
    name: '4-digit-numeric',
    baseConfidence: 65,
    minLength: 4,
    maxLength: 4,
    isNumeric: true,
    providers: ['SMS', 'Telegram', 'Banking'],
    description: '4-digit numeric code',
  },
  {
    pattern: /\b\d{5}\b/g,
    name: '5-digit-numeric',
    baseConfidence: 60,
    minLength: 5,
    maxLength: 5,
    isNumeric: true,
    providers: ['Telegram', 'WhatsApp'],
    description: '5-digit numeric code',
  },
  {
    pattern: /\b\d{6}\b/g,
    name: '6-digit-numeric',
    baseConfidence: 80,
    minLength: 6,
    maxLength: 6,
    isNumeric: true,
    providers: ['Google', 'Microsoft', 'Apple', 'Amazon'],
    description: '6-digit numeric code (most common)',
  },
  {
    pattern: /\b\d{7}\b/g,
    name: '7-digit-numeric',
    baseConfidence: 50,
    minLength: 7,
    maxLength: 7,
    isNumeric: true,
    providers: ['Banking'],
    description: '7-digit numeric code',
  },
  {
    pattern: /\b\d{8}\b/g,
    name: '8-digit-numeric',
    baseConfidence: 55,
    minLength: 8,
    maxLength: 8,
    isNumeric: true,
    providers: ['Banking'],
    description: '8-digit numeric code',
  },

  // Formatted patterns
  {
    pattern: /\b\d{3}[-\s]\d{3}\b/g,
    name: '3-3-formatted',
    baseConfidence: 80,
    minLength: 7,
    maxLength: 7,
    isNumeric: true,
    description: '3-3 formatted (123-456)',
  },
  {
    pattern: /\b\d{4}[-\s]\d{4}\b/g,
    name: '4-4-formatted',
    baseConfidence: 70,
    minLength: 9,
    maxLength: 9,
    isNumeric: true,
    description: '4-4 formatted',
  },
  {
    pattern: /\b\d{2}[-\s]\d{2}[-\s]\d{2}\b/g,
    name: '2-2-2-formatted',
    baseConfidence: 65,
    minLength: 8,
    maxLength: 8,
    isNumeric: true,
    description: '2-2-2 formatted',
  },

  // Alphanumeric patterns
  {
    pattern: /\b[A-Z0-9]{4}\b/g,
    name: '4-char-alphanumeric',
    baseConfidence: 50,
    minLength: 4,
    maxLength: 4,
    isNumeric: false,
    description: '4-character alphanumeric',
  },
  {
    pattern: /\b[A-Z0-9]{5}\b/g,
    name: '5-char-alphanumeric',
    baseConfidence: 50,
    minLength: 5,
    maxLength: 5,
    isNumeric: false,
    description: '5-character alphanumeric',
  },
  {
    pattern: /\b[A-Z0-9]{6}\b/g,
    name: '6-char-alphanumeric',
    baseConfidence: 60,
    minLength: 6,
    maxLength: 6,
    isNumeric: false,
    description: '6-character alphanumeric',
  },
  {
    pattern: /\b[A-Z0-9]{8}\b/g,
    name: '8-char-alphanumeric',
    baseConfidence: 55,
    minLength: 8,
    maxLength: 8,
    isNumeric: false,
    description: '8-character alphanumeric',
  },

  // Provider-specific patterns (HIGH CONFIDENCE)
  {
    pattern: /\bG-\d{6}\b/g,
    name: 'google-prefix',
    baseConfidence: 98,
    minLength: 8,
    maxLength: 8,
    isNumeric: false,
    providers: ['Google'],
    description: 'Google-specific (G-123456)',
  },
  {
    pattern: /\bMSFT\d{6}\b/g,
    name: 'microsoft-prefix',
    baseConfidence: 98,
    minLength: 10,
    maxLength: 10,
    isNumeric: false,
    providers: ['Microsoft'],
    description: 'Microsoft-specific',
  },
  {
    pattern: /\bAAPL\d{6}\b/g,
    name: 'apple-prefix',
    baseConfidence: 95,
    minLength: 10,
    maxLength: 10,
    isNumeric: false,
    providers: ['Apple'],
    description: 'Apple-specific',
  },
  {
    pattern: /\bAMZN\d{6}\b/g,
    name: 'amazon-prefix',
    baseConfidence: 95,
    minLength: 10,
    maxLength: 10,
    isNumeric: false,
    providers: ['Amazon'],
    description: 'Amazon-specific',
  },
  {
    pattern: /\bFB-\d{6}\b/g,
    name: 'facebook-prefix',
    baseConfidence: 95,
    minLength: 9,
    maxLength: 9,
    isNumeric: false,
    providers: ['Facebook'],
    description: 'Facebook-specific',
  },
  {
    pattern: /\bGH-\d{6}\b/g,
    name: 'github-prefix',
    baseConfidence: 95,
    minLength: 9,
    maxLength: 9,
    isNumeric: false,
    providers: ['GitHub'],
    description: 'GitHub-specific',
  },
  {
    pattern: /\bPYPL\d{6}\b/g,
    name: 'paypal-prefix',
    baseConfidence: 95,
    minLength: 10,
    maxLength: 10,
    isNumeric: false,
    providers: ['PayPal'],
    description: 'PayPal-specific',
  },
  {
    pattern: /\bTLM\d{5}\b/g,
    name: 'telegram-prefix',
    baseConfidence: 95,
    minLength: 8,
    maxLength: 8,
    isNumeric: false,
    providers: ['Telegram'],
    description: 'Telegram-specific',
  },
  {
    pattern: /\bWA-\d{6}\b/g,
    name: 'whatsapp-prefix',
    baseConfidence: 95,
    minLength: 9,
    maxLength: 9,
    isNumeric: false,
    providers: ['WhatsApp'],
    description: 'WhatsApp-specific',
  },
  {
    pattern: /\bUBR\d{6}\b/g,
    name: 'uber-prefix',
    baseConfidence: 90,
    minLength: 9,
    maxLength: 9,
    isNumeric: false,
    providers: ['Uber'],
    description: 'Uber-specific',
  },
  {
    pattern: /\bABNB\d{6}\b/g,
    name: 'airbnb-prefix',
    baseConfidence: 90,
    minLength: 10,
    maxLength: 10,
    isNumeric: false,
    providers: ['Airbnb'],
    description: 'Airbnb-specific',
  },
  {
    pattern: /\bNFLX\d{6}\b/g,
    name: 'netflix-prefix',
    baseConfidence: 90,
    minLength: 10,
    maxLength: 10,
    isNumeric: false,
    providers: ['Netflix'],
    description: 'Netflix-specific',
  },
  {
    pattern: /\bCOIN\d{6}\b/g,
    name: 'coinbase-prefix',
    baseConfidence: 90,
    minLength: 10,
    maxLength: 10,
    isNumeric: false,
    providers: ['Coinbase'],
    description: 'Coinbase-specific',
  },
  {
    pattern: /\bSWGY\d{6}\b/g,
    name: 'swiggy-prefix',
    baseConfidence: 90,
    minLength: 10,
    maxLength: 10,
    isNumeric: false,
    providers: ['Swiggy'],
    description: 'Swiggy-specific',
  },
  {
    pattern: /\bZMTO\d{6}\b/g,
    name: 'zomato-prefix',
    baseConfidence: 90,
    minLength: 10,
    maxLength: 10,
    isNumeric: false,
    providers: ['Zomato'],
    description: 'Zomato-specific',
  },
  {
    pattern: /\bFLPK\d{6}\b/g,
    name: 'flipkart-prefix',
    baseConfidence: 90,
    minLength: 10,
    maxLength: 10,
    isNumeric: false,
    providers: ['Flipkart'],
    description: 'Flipkart-specific',
  },
  {
    pattern: /\bPAYTM\d{6}\b/g,
    name: 'paytm-prefix',
    baseConfidence: 90,
    minLength: 11,
    maxLength: 11,
    isNumeric: false,
    providers: ['Paytm'],
    description: 'Paytm-specific',
  },
];
