import type { ProviderKnowledge } from '../../types/extraction.types';

export const PROVIDER_DATABASE: ProviderKnowledge[] = [
  // ────────────────────────────────────────────────────────────
  //  BIG TECH (FAANG + Microsoft)
  // ────────────────────────────────────────────────────────────
  {
    name: 'Google',
    domains: ['google.com', 'gmail.com', 'accounts.google.com', 'youtube.com', 'android.com'],
    senderPatterns: [/google.*@.*\.com/i, /accounts-noreply@google\.com/i, /noreply@google\.com/i],
    subjectPatterns: [
      /google.*verification.*code/i,
      /sign[- ]?in.*attempt/i,
      /security.*alert/i,
      /2[- ]?step.*verification/i,
    ],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/accounts\.google\.com.*\/o\/oauth/i, /myaccount\.google\.com/i],
    commonPhrases: [
      'G-',
      'Google verification code',
      'Never share your code',
      'Someone tried to sign in',
      '2-Step Verification',
    ],
    confidence: 98,
    industry: 'Technology',
    country: 'USA',
  },
  {
    name: 'Microsoft',
    domains: [
      'microsoft.com',
      'account.microsoft.com',
      'login.microsoftonline.com',
      'outlook.com',
      'live.com',
      'hotmail.com',
      'xbox.com',
    ],
    senderPatterns: [
      /microsoft.*@.*\.com/i,
      /account.*microsoft/i,
      /no-reply@account\.microsoft\.com/i,
    ],
    subjectPatterns: [
      /microsoft.*security.*code/i,
      /verification.*code.*microsoft/i,
      /sign[- ]?in.*microsoft/i,
    ],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/login\.microsoftonline\.com/i, /account\.microsoft\.com/i],
    commonPhrases: [
      'Microsoft verification code',
      'Your security code',
      'Two-step verification',
      'Protect your account',
    ],
    confidence: 98,
    industry: 'Technology',
    country: 'USA',
  },
  {
    name: 'Apple',
    domains: ['apple.com', 'icloud.com', 'appleid.apple.com', 'me.com', 'mac.com'],
    senderPatterns: [/apple.*@.*\.com/i, /no_reply.*apple/i, /appleid@id\.apple\.com/i],
    subjectPatterns: [
      /apple.*id.*code/i,
      /verification.*code.*apple/i,
      /sign[- ]?in.*attempt.*apple/i,
    ],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/appleid\.apple\.com/i, /icloud\.com/i],
    commonPhrases: ['Apple ID', 'Verification code', 'Sign-in attempt', 'Your Apple ID code'],
    confidence: 98,
    industry: 'Technology',
    country: 'USA',
  },
  {
    name: 'Amazon',
    domains: [
      'amazon.com',
      'amazon.co.uk',
      'amazon.in',
      'amazon.de',
      'amazon.fr',
      'amazon.co.jp',
      'aws.amazon.com',
    ],
    senderPatterns: [/amazon.*@.*\.com/i, /no-reply.*amazon/i, /aws-noreply@amazon\.com/i],
    subjectPatterns: [/amazon.*verification.*code/i, /otp.*amazon/i, /security.*code.*amazon/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/amazon\.[a-z]+.*\/ap\/verify/i, /amazon.*otp/i],
    commonPhrases: ['Amazon verification code', 'OTP', 'One time password', 'Your Amazon code'],
    confidence: 98,
    industry: 'E-commerce',
    country: 'USA',
  },
  {
    name: 'Meta',
    domains: [
      'facebook.com',
      'fb.com',
      'meta.com',
      'facebookmail.com',
      'instagram.com',
      'whatsapp.com',
    ],
    senderPatterns: [
      /facebook.*@.*\.com/i,
      /security.*facebook/i,
      /notify@facebookmail\.com/i,
      /instagram.*@.*\.com/i,
    ],
    subjectPatterns: [
      /facebook.*code/i,
      /security.*code.*facebook/i,
      /confirm.*identity.*facebook/i,
      /instagram.*code/i,
    ],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/facebook\.com.*\/login\.php/i, /fb\.com/i, /instagram\.com/i],
    commonPhrases: ['Facebook code', 'Security code', 'Confirm your identity', 'Instagram code'],
    confidence: 98,
    industry: 'Social Media',
    country: 'USA',
  },

  // ────────────────────────────────────────────────────────────
  //  COMMUNICATION & MESSAGING
  // ────────────────────────────────────────────────────────────
  {
    name: 'WhatsApp',
    domains: ['whatsapp.com', 'whatsapp.net'],
    senderPatterns: [/whatsapp.*@.*\.com/i, /noreply@whatsapp\.com/i],
    subjectPatterns: [
      /whatsapp.*code/i,
      /verification.*code.*whatsapp/i,
      /whatsapp.*verification/i,
    ],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/whatsapp\.com.*\/verify/i],
    commonPhrases: ['WhatsApp code', 'verification code', 'Do not share', 'Your WhatsApp'],
    confidence: 95,
    industry: 'Communication',
    country: 'USA',
  },
  {
    name: 'Telegram',
    domains: ['telegram.org'],
    senderPatterns: [/telegram.*@.*\.org/i, /noreply@telegram\.org/i],
    subjectPatterns: [/telegram.*code/i, /login.*code.*telegram/i, /telegram.*verification/i],
    emailIntent: 'verification',
    otpLength: 5,
    otpFormat: 'numeric',
    linkPatterns: [/telegram\.org/i],
    commonPhrases: ['Telegram code', 'login code', 'Your Telegram'],
    confidence: 95,
    industry: 'Communication',
    country: 'UK',
  },
  {
    name: 'Discord',
    domains: ['discord.com', 'discordapp.com'],
    senderPatterns: [/discord.*@.*\.com/i, /noreply@discord\.com/i],
    subjectPatterns: [/discord.*code/i, /verification.*discord/i, /discord.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/discord\.com.*\/verify/i],
    commonPhrases: ['Discord verification code', 'Your code', 'Discord code'],
    confidence: 95,
    industry: 'Communication',
    country: 'USA',
  },
  {
    name: 'Slack',
    domains: ['slack.com'],
    senderPatterns: [/slack.*@.*\.com/i, /noreply@slack\.com/i],
    subjectPatterns: [
      /slack.*code/i,
      /verification.*slack/i,
      /slack.*verification/i,
      /sign[- ]?in.*slack/i,
    ],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/slack\.com.*\/verify/i],
    commonPhrases: ['Slack verification code', 'Sign in code', 'Slack code'],
    confidence: 95,
    industry: 'Communication',
    country: 'USA',
  },
  {
    name: 'Zoom',
    domains: ['zoom.us'],
    senderPatterns: [/zoom.*@.*\.us/i, /noreply@zoom\.us/i],
    subjectPatterns: [/zoom.*code/i, /verification.*zoom/i, /zoom.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/zoom\.us.*\/verify/i],
    commonPhrases: ['Zoom verification code', 'Your code', 'Zoom code'],
    confidence: 95,
    industry: 'Communication',
    country: 'USA',
  },
  {
    name: 'Skype',
    domains: ['skype.com', 'microsoft.com'],
    senderPatterns: [/skype.*@.*\.com/i, /noreply@skype\.com/i],
    subjectPatterns: [/skype.*code/i, /verification.*skype/i, /skype.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/skype\.com.*\/verify/i],
    commonPhrases: ['Skype verification code', 'Your code', 'Skype code'],
    confidence: 95,
    industry: 'Communication',
    country: 'USA',
  },
  {
    name: 'Snapchat',
    domains: ['snapchat.com', 'snap.com'],
    senderPatterns: [/snapchat.*@.*\.com/i, /noreply@snapchat\.com/i],
    subjectPatterns: [/snapchat.*code/i, /verification.*snapchat/i, /snapchat.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/snapchat\.com.*\/verify/i],
    commonPhrases: ['Snapchat verification code', 'Your code', 'Snapchat code'],
    confidence: 95,
    industry: 'Social Media',
    country: 'USA',
  },
  {
    name: 'Twitter',
    domains: ['twitter.com', 'x.com'],
    senderPatterns: [/@twitter\.com/i, /@e\.twitter\.com/i, /@x\.com/i, /verify@twitter\.com/i],
    subjectPatterns: [
      /twitter.*code/i,
      /verification.*twitter/i,
      /x.*code/i,
      /twitter.*verification/i,
    ],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/twitter\.com.*\/verify/i, /x\.com.*\/verify/i],
    commonPhrases: ['Twitter code', 'verification code', 'X code', 'Twitter verification'],
    confidence: 95,
    industry: 'Social Media',
    country: 'USA',
  },
  {
    name: 'LinkedIn',
    domains: ['linkedin.com'],
    senderPatterns: [/linkedin.*@.*\.com/i, /messages.*linkedin/i, /no-reply@linkedin\.com/i],
    subjectPatterns: [/linkedin.*code/i, /verification.*linkedin/i, /linkedin.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/linkedin\.com.*\/verify/i],
    commonPhrases: ['LinkedIn verification code', 'Your verification code', 'LinkedIn code'],
    confidence: 95,
    industry: 'Professional Network',
    country: 'USA',
  },
  {
    name: 'Mozilla/Firefox',
    domains: ['mozilla.org', 'firefox.com', 'accounts.firefox.com'],
    senderPatterns: [/accounts@firefox\.com/i, /mozilla/i],
    subjectPatterns: [/confirm.*account/i, /verification/i, /security.*code/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/accounts\.firefox\.com/i],
    commonPhrases: ['confirm your account', 'verification code', 'Firefox code'],
    confidence: 95,
    industry: 'Technology',
    country: 'USA',
  },
  {
    name: 'Pinterest',
    domains: ['pinterest.com'],
    senderPatterns: [/pinterest.*@.*\.com/i, /noreply@pinterest\.com/i],
    subjectPatterns: [/pinterest.*code/i, /verification.*pinterest/i, /pinterest.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/pinterest\.com.*\/verify/i],
    commonPhrases: ['Pinterest verification code', 'Your code', 'Pinterest code'],
    confidence: 95,
    industry: 'Social Media',
    country: 'USA',
  },
  {
    name: 'TikTok',
    domains: ['tiktok.com'],
    senderPatterns: [/tiktok.*@.*\.com/i, /noreply@tiktok\.com/i],
    subjectPatterns: [/tiktok.*code/i, /verification.*tiktok/i, /tiktok.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/tiktok\.com.*\/verify/i],
    commonPhrases: ['TikTok verification code', 'Your code', 'TikTok code'],
    confidence: 95,
    industry: 'Social Media',
    country: 'China',
  },
  {
    name: 'Reddit',
    domains: ['reddit.com'],
    senderPatterns: [/reddit.*@.*\.com/i, /noreply@reddit\.com/i],
    subjectPatterns: [/reddit.*code/i, /verification.*reddit/i, /reddit.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/reddit\.com.*\/verify/i],
    commonPhrases: ['Reddit verification code', 'Your code', 'Reddit code'],
    confidence: 95,
    industry: 'Social Media',
    country: 'USA',
  },

  // ────────────────────────────────────────────────────────────
  //  FINANCIAL SERVICES
  // ────────────────────────────────────────────────────────────
  {
    name: 'PayPal',
    domains: ['paypal.com', 'paypal.co.uk', 'paypal.de', 'paypal.fr', 'paypal.ca', 'paypal.com.au'],
    senderPatterns: [/paypal.*@.*\.com/i, /service.*paypal/i, /no-reply@paypal\.com/i],
    subjectPatterns: [
      /paypal.*security.*code/i,
      /verification.*code.*paypal/i,
      /paypal.*verification/i,
    ],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/paypal\.[a-z]+.*\/verify/i],
    commonPhrases: [
      'PayPal security code',
      'verification code',
      'Protect your account',
      'Your PayPal',
    ],
    confidence: 98,
    industry: 'Financial',
    country: 'USA',
  },
  {
    name: 'Stripe',
    domains: ['stripe.com'],
    senderPatterns: [/stripe.*@.*\.com/i, /noreply@stripe\.com/i],
    subjectPatterns: [/stripe.*code/i, /verification.*stripe/i, /stripe.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/stripe\.com.*\/verify/i],
    commonPhrases: ['Stripe verification code', 'Your code', 'Stripe code'],
    confidence: 95,
    industry: 'Financial',
    country: 'USA',
  },
  {
    name: 'Square',
    domains: ['squareup.com', 'square.com'],
    senderPatterns: [/square.*@.*\.com/i, /noreply@squareup\.com/i],
    subjectPatterns: [/square.*code/i, /verification.*square/i, /square.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/squareup\.com.*\/verify/i],
    commonPhrases: ['Square verification code', 'Your code', 'Square code'],
    confidence: 95,
    industry: 'Financial',
    country: 'USA',
  },
  {
    name: 'Coinbase',
    domains: ['coinbase.com'],
    senderPatterns: [/coinbase.*@.*\.com/i, /noreply@coinbase\.com/i],
    subjectPatterns: [
      /coinbase.*code/i,
      /verification.*coinbase/i,
      /coinbase.*verification/i,
      /2fa.*coinbase/i,
    ],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/coinbase\.com.*\/verify/i],
    commonPhrases: ['Coinbase verification code', 'Your code', 'Coinbase code', '2FA code'],
    confidence: 95,
    industry: 'Cryptocurrency',
    country: 'USA',
  },
  {
    name: 'Binance',
    domains: ['binance.com'],
    senderPatterns: [/binance.*@.*\.com/i, /noreply@binance\.com/i],
    subjectPatterns: [
      /binance.*code/i,
      /verification.*binance/i,
      /binance.*verification/i,
      /2fa.*binance/i,
    ],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/binance\.com.*\/verify/i],
    commonPhrases: ['Binance verification code', 'Your code', 'Binance code', '2FA code'],
    confidence: 95,
    industry: 'Cryptocurrency',
    country: 'Malta',
  },
  {
    name: 'Robinhood',
    domains: ['robinhood.com'],
    senderPatterns: [/robinhood.*@.*\.com/i, /noreply@robinhood\.com/i],
    subjectPatterns: [/robinhood.*code/i, /verification.*robinhood/i, /robinhood.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/robinhood\.com.*\/verify/i],
    commonPhrases: ['Robinhood verification code', 'Your code', 'Robinhood code'],
    confidence: 95,
    industry: 'Financial',
    country: 'USA',
  },
  {
    name: 'Chase',
    domains: ['chase.com', 'jpmorganchase.com'],
    senderPatterns: [/chase.*@.*\.com/i, /noreply@chase\.com/i],
    subjectPatterns: [
      /chase.*code/i,
      /verification.*chase/i,
      /chase.*verification/i,
      /security.*chase/i,
    ],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/chase\.com.*\/verify/i],
    commonPhrases: ['Chase verification code', 'Your code', 'Chase code', 'Security code'],
    confidence: 95,
    industry: 'Banking',
    country: 'USA',
  },
  {
    name: 'Bank of America',
    domains: ['bankofamerica.com', 'bofa.com'],
    senderPatterns: [/bankofamerica.*@.*\.com/i, /noreply@bankofamerica\.com/i],
    subjectPatterns: [/bank.*code/i, /verification.*bank/i, /bofa.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/bankofamerica\.com.*\/verify/i],
    commonPhrases: ['Bank of America verification code', 'Your code', 'BofA code'],
    confidence: 95,
    industry: 'Banking',
    country: 'USA',
  },
  {
    name: 'Wells Fargo',
    domains: ['wellsfargo.com'],
    senderPatterns: [/wellsfargo.*@.*\.com/i, /noreply@wellsfargo\.com/i],
    subjectPatterns: [/wells.*code/i, /verification.*wells/i, /wellsfargo.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/wellsfargo\.com.*\/verify/i],
    commonPhrases: ['Wells Fargo verification code', 'Your code', 'Wells Fargo code'],
    confidence: 95,
    industry: 'Banking',
    country: 'USA',
  },
  {
    name: 'Citibank',
    domains: ['citibank.com', 'citi.com'],
    senderPatterns: [/citibank.*@.*\.com/i, /noreply@citibank\.com/i, /citi.*@.*\.com/i],
    subjectPatterns: [/citi.*code/i, /verification.*citi/i, /citibank.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/citibank\.com.*\/verify/i, /citi\.com.*\/verify/i],
    commonPhrases: ['Citibank verification code', 'Your code', 'Citi code'],
    confidence: 95,
    industry: 'Banking',
    country: 'USA',
  },

  // ────────────────────────────────────────────────────────────
  //  ENTERTAINMENT & STREAMING
  // ────────────────────────────────────────────────────────────
  {
    name: 'Netflix',
    domains: ['netflix.com'],
    senderPatterns: [/netflix.*@.*\.com/i, /info@netflix\.com/i],
    subjectPatterns: [/netflix.*code/i, /verification.*netflix/i, /netflix.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/netflix\.com.*\/verify/i],
    commonPhrases: ['Netflix verification code', 'Your code', 'Netflix code'],
    confidence: 95,
    industry: 'Entertainment',
    country: 'USA',
  },
  {
    name: 'Spotify',
    domains: ['spotify.com'],
    senderPatterns: [/spotify.*@.*\.com/i, /no-reply@spotify\.com/i],
    subjectPatterns: [/spotify.*code/i, /verification.*spotify/i, /spotify.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/spotify\.com.*\/verify/i],
    commonPhrases: ['Spotify verification code', 'Your code', 'Spotify code'],
    confidence: 95,
    industry: 'Entertainment',
    country: 'Sweden',
  },
  {
    name: 'Hulu',
    domains: ['hulu.com'],
    senderPatterns: [/hulu.*@.*\.com/i, /noreply@hulu\.com/i],
    subjectPatterns: [/hulu.*code/i, /verification.*hulu/i, /hulu.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/hulu\.com.*\/verify/i],
    commonPhrases: ['Hulu verification code', 'Your code', 'Hulu code'],
    confidence: 95,
    industry: 'Entertainment',
    country: 'USA',
  },
  {
    name: 'Disney+',
    domains: ['disneyplus.com', 'disney.com'],
    senderPatterns: [/disney.*@.*\.com/i, /noreply@disneyplus\.com/i],
    subjectPatterns: [/disney.*code/i, /verification.*disney/i, /disneyplus.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/disneyplus\.com.*\/verify/i],
    commonPhrases: ['Disney+ verification code', 'Your code', 'Disney code'],
    confidence: 95,
    industry: 'Entertainment',
    country: 'USA',
  },
  {
    name: 'HBO Max',
    domains: ['hbomax.com', 'hbo.com'],
    senderPatterns: [/hbo.*@.*\.com/i, /noreply@hbomax\.com/i],
    subjectPatterns: [/hbo.*code/i, /verification.*hbo/i, /hbomax.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/hbomax\.com.*\/verify/i],
    commonPhrases: ['HBO Max verification code', 'Your code', 'HBO code'],
    confidence: 95,
    industry: 'Entertainment',
    country: 'USA',
  },
  {
    name: 'Prime Video',
    domains: ['primevideo.com', 'amazon.com'],
    senderPatterns: [/primevideo.*@.*\.com/i, /noreply@primevideo\.com/i],
    subjectPatterns: [/prime.*code/i, /verification.*prime/i, /primevideo.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/primevideo\.com.*\/verify/i],
    commonPhrases: ['Prime Video verification code', 'Your code', 'Prime code'],
    confidence: 95,
    industry: 'Entertainment',
    country: 'USA',
  },
  {
    name: 'Twitch',
    domains: ['twitch.tv', 'twitchcon.com'],
    senderPatterns: [/twitch.*@.*\.tv/i, /noreply@twitch\.tv/i],
    subjectPatterns: [/twitch.*code/i, /verification.*twitch/i, /twitch.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/twitch\.tv.*\/verify/i],
    commonPhrases: ['Twitch verification code', 'Your code', 'Twitch code'],
    confidence: 95,
    industry: 'Entertainment',
    country: 'USA',
  },
  {
    name: 'YouTube',
    domains: ['youtube.com', 'google.com'],
    senderPatterns: [/youtube.*@.*\.com/i, /noreply@youtube\.com/i],
    subjectPatterns: [/youtube.*code/i, /verification.*youtube/i, /youtube.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/youtube\.com.*\/verify/i],
    commonPhrases: ['YouTube verification code', 'Your code', 'YouTube code'],
    confidence: 95,
    industry: 'Entertainment',
    country: 'USA',
  },

  // ────────────────────────────────────────────────────────────
  //  E-COMMERCE & RETAIL
  // ────────────────────────────────────────────────────────────
  {
    name: 'eBay',
    domains: ['ebay.com', 'ebay.co.uk', 'ebay.de', 'ebay.in'],
    senderPatterns: [/ebay.*@.*\.com/i, /noreply@ebay\.com/i],
    subjectPatterns: [/ebay.*code/i, /verification.*ebay/i, /ebay.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/ebay\.[a-z]+.*\/verify/i],
    commonPhrases: ['eBay verification code', 'Your code', 'eBay code'],
    confidence: 95,
    industry: 'E-commerce',
    country: 'USA',
  },
  {
    name: 'Etsy',
    domains: ['etsy.com'],
    senderPatterns: [/etsy.*@.*\.com/i, /noreply@etsy\.com/i],
    subjectPatterns: [/etsy.*code/i, /verification.*etsy/i, /etsy.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/etsy\.com.*\/verify/i],
    commonPhrases: ['Etsy verification code', 'Your code', 'Etsy code'],
    confidence: 95,
    industry: 'E-commerce',
    country: 'USA',
  },
  {
    name: 'Shopify',
    domains: ['shopify.com', 'myshopify.com'],
    senderPatterns: [/shopify.*@.*\.com/i, /noreply@shopify\.com/i],
    subjectPatterns: [/shopify.*code/i, /verification.*shopify/i, /shopify.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/shopify\.com.*\/verify/i],
    commonPhrases: ['Shopify verification code', 'Your code', 'Shopify code'],
    confidence: 95,
    industry: 'E-commerce',
    country: 'Canada',
  },
  {
    name: 'Walmart',
    domains: ['walmart.com'],
    senderPatterns: [/walmart.*@.*\.com/i, /noreply@walmart\.com/i],
    subjectPatterns: [/walmart.*code/i, /verification.*walmart/i, /walmart.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/walmart\.com.*\/verify/i],
    commonPhrases: ['Walmart verification code', 'Your code', 'Walmart code'],
    confidence: 95,
    industry: 'Retail',
    country: 'USA',
  },
  {
    name: 'Target',
    domains: ['target.com'],
    senderPatterns: [/target.*@.*\.com/i, /noreply@target\.com/i],
    subjectPatterns: [/target.*code/i, /verification.*target/i, /target.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/target\.com.*\/verify/i],
    commonPhrases: ['Target verification code', 'Your code', 'Target code'],
    confidence: 95,
    industry: 'Retail',
    country: 'USA',
  },
  {
    name: 'Alibaba',
    domains: ['alibaba.com', 'aliexpress.com'],
    senderPatterns: [/alibaba.*@.*\.com/i, /noreply@alibaba\.com/i],
    subjectPatterns: [/alibaba.*code/i, /verification.*alibaba/i, /alibaba.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/alibaba\.com.*\/verify/i],
    commonPhrases: ['Alibaba verification code', 'Your code', 'Alibaba code'],
    confidence: 95,
    industry: 'E-commerce',
    country: 'China',
  },

  // ────────────────────────────────────────────────────────────
  //  TRAVEL & TRANSPORTATION
  // ────────────────────────────────────────────────────────────
  {
    name: 'Uber',
    domains: ['uber.com', 'uberinternal.com'],
    senderPatterns: [/uber.*@.*\.com/i, /no-reply.*uber/i],
    subjectPatterns: [/uber.*code/i, /verification.*uber/i, /uber.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/uber\.com.*\/verify/i],
    commonPhrases: ['Your Uber code', 'verification code', 'Uber code'],
    confidence: 95,
    industry: 'Transportation',
    country: 'USA',
  },
  {
    name: 'Lyft',
    domains: ['lyft.com'],
    senderPatterns: [/lyft.*@.*\.com/i, /noreply@lyft\.com/i],
    subjectPatterns: [/lyft.*code/i, /verification.*lyft/i, /lyft.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/lyft\.com.*\/verify/i],
    commonPhrases: ['Lyft verification code', 'Your code', 'Lyft code'],
    confidence: 95,
    industry: 'Transportation',
    country: 'USA',
  },
  {
    name: 'Airbnb',
    domains: ['airbnb.com'],
    senderPatterns: [/airbnb.*@.*\.com/i, /noreply@airbnb\.com/i],
    subjectPatterns: [/airbnb.*code/i, /verification.*airbnb/i, /airbnb.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/airbnb\.com.*\/verify/i],
    commonPhrases: ['Airbnb verification code', 'Your code', 'Airbnb code'],
    confidence: 95,
    industry: 'Travel',
    country: 'USA',
  },
  {
    name: 'Booking.com',
    domains: ['booking.com'],
    senderPatterns: [/booking.*@.*\.com/i, /noreply@booking\.com/i],
    subjectPatterns: [/booking.*code/i, /verification.*booking/i, /booking\.com.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/booking\.com.*\/verify/i],
    commonPhrases: ['Booking.com verification code', 'Your code', 'Booking code'],
    confidence: 95,
    industry: 'Travel',
    country: 'Netherlands',
  },
  {
    name: 'Expedia',
    domains: ['expedia.com'],
    senderPatterns: [/expedia.*@.*\.com/i, /noreply@expedia\.com/i],
    subjectPatterns: [/expedia.*code/i, /verification.*expedia/i, /expedia.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/expedia\.com.*\/verify/i],
    commonPhrases: ['Expedia verification code', 'Your code', 'Expedia code'],
    confidence: 95,
    industry: 'Travel',
    country: 'USA',
  },
  {
    name: 'Delta Airlines',
    domains: ['delta.com'],
    senderPatterns: [/delta.*@.*\.com/i, /noreply@delta\.com/i],
    subjectPatterns: [/delta.*code/i, /verification.*delta/i, /delta.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/delta\.com.*\/verify/i],
    commonPhrases: ['Delta verification code', 'Your code', 'Delta code'],
    confidence: 95,
    industry: 'Airlines',
    country: 'USA',
  },
  {
    name: 'United Airlines',
    domains: ['united.com'],
    senderPatterns: [/united.*@.*\.com/i, /noreply@united\.com/i],
    subjectPatterns: [/united.*code/i, /verification.*united/i, /united.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/united\.com.*\/verify/i],
    commonPhrases: ['United verification code', 'Your code', 'United code'],
    confidence: 95,
    industry: 'Airlines',
    country: 'USA',
  },
  {
    name: 'ICIMS',
    domains: ['icims.com', 'clicks.icims.com'],
    senderPatterns: [/icims.*@.*\.com/i, /noreply@icims\.com/i],
    subjectPatterns: [/verify.*email/i, /confirm.*identity/i, /verification/i],
    emailIntent: 'activation',
    linkPatterns: [/icims\.com\/verify/i, /clicks\.icims\.com/i],
    commonPhrases: ['verify your email', 'icims verify', 'complete your registration'],
    confidence: 90,
    industry: 'HR Technology',
    country: 'USA',
  },
  {
    name: 'American Airlines',
    domains: ['aa.com', 'americanairlines.com'],
    senderPatterns: [/american.*@.*\.com/i, /noreply@aa\.com/i],
    subjectPatterns: [/american.*code/i, /verification.*american/i, /aa.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/aa\.com.*\/verify/i],
    commonPhrases: ['American Airlines verification code', 'Your code', 'AA code'],
    confidence: 95,
    industry: 'Airlines',
    country: 'USA',
  },

  // ────────────────────────────────────────────────────────────
  //  AI & DEVELOPER SERVICES
  // ────────────────────────────────────────────────────────────
  {
    name: 'Qwen',
    domains: ['qwen.ai', 'aliyun.com', 'alibaba.com', 'qwenlm.ai'],
    senderPatterns: [/qwen.*@.*\.com/i, /noreply.*qwen/i, /admin.*qwen/i],
    subjectPatterns: [
      /qwen.*code/i,
      /verification.*qwen/i,
      /qwen.*verification/i,
      /active.*mail/i,
      /activation.*mail/i,
    ],
    emailIntent: 'activation',
    linkPatterns: [/qwen\.ai.*\/verify/i, /qwenlm\.ai/i],
    commonPhrases: ['Qwen verification code', 'Your code', 'Qwen code', 'active mail'],
    confidence: 95,
    industry: 'Technology',
    country: 'China',
  },
  {
    name: 'OpenAI',
    domains: ['openai.com', 'chatgpt.com'],
    senderPatterns: [/openai.*@.*\.com/i, /noreply.*openai/i],
    subjectPatterns: [/openai.*code/i, /verification.*openai/i, /openai.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/openai\.com.*\/verify/i, /chatgpt\.com/i],
    commonPhrases: ['OpenAI verification code', 'Your code', 'OpenAI code'],
    confidence: 95,
    industry: 'Technology',
    country: 'USA',
  },
  {
    name: 'Anthropic',
    domains: ['anthropic.com', 'claude.ai'],
    senderPatterns: [/anthropic.*@.*\.com/i, /noreply.*anthropic/i, /noreply.*claude/i],
    subjectPatterns: [
      /anthropic.*code/i,
      /verification.*anthropic/i,
      /claude.*verification/i,
      /sign.*in.*claude/i,
    ],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'alphanumeric',
    linkPatterns: [/claude\.ai.*\/verify/i, /anthropic\.com/i],
    commonPhrases: ['Anthropic verification code', 'Your code', 'login code'],
    confidence: 95,
    industry: 'Technology',
    country: 'USA',
  },
  {
    name: 'GitHub',
    domains: ['github.com'],
    senderPatterns: [/github.*@.*\.com/i, /noreply.*github/i, /noreply@github\.com/i],
    subjectPatterns: [/github.*code/i, /verification.*github/i, /github.*otp/i, /github.*2fa/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/github\.com.*\/verify/i],
    commonPhrases: ['GitHub verification code', 'Two-factor authentication', 'GitHub code'],
    confidence: 98,
    industry: 'Technology',
    country: 'USA',
  },
  {
    name: 'GitLab',
    domains: ['gitlab.com'],
    senderPatterns: [/gitlab.*@.*\.com/i, /noreply@gitlab\.com/i],
    subjectPatterns: [/gitlab.*code/i, /verification.*gitlab/i, /gitlab.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/gitlab\.com.*\/verify/i],
    commonPhrases: ['GitLab verification code', 'Your code', 'GitLab code'],
    confidence: 95,
    industry: 'Technology',
    country: 'USA',
  },
  {
    name: 'Bitbucket',
    domains: ['bitbucket.org', 'atlassian.com'],
    senderPatterns: [/bitbucket.*@.*\.org/i, /noreply@bitbucket\.org/i],
    subjectPatterns: [/bitbucket.*code/i, /verification.*bitbucket/i, /bitbucket.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/bitbucket\.org.*\/verify/i],
    commonPhrases: ['Bitbucket verification code', 'Your code', 'Bitbucket code'],
    confidence: 95,
    industry: 'Technology',
    country: 'Australia',
  },
  {
    name: 'AWS',
    domains: ['amazon.com', 'amazonaws.com'],
    senderPatterns: [/aws-noreply@amazon\.com/i, /no-reply@amazonaws\.com/i],
    subjectPatterns: [/aws.*code/i, /verification.*aws/i, /amazon.*web.*services.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/aws\.amazon\.com.*\/verify/i],
    commonPhrases: ['AWS verification code', 'Your code', 'Amazon Web Services code'],
    confidence: 98,
    industry: 'Cloud Services',
    country: 'USA',
  },
  {
    name: 'Google Cloud',
    domains: ['google.com', 'cloud.google.com'],
    senderPatterns: [/google-cloud.*@.*\.com/i, /noreply@google\.com/i],
    subjectPatterns: [/google.*cloud.*code/i, /verification.*google.*cloud/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/cloud\.google\.com.*\/verify/i],
    commonPhrases: ['Google Cloud verification code', 'Your code', 'GCP code'],
    confidence: 98,
    industry: 'Cloud Services',
    country: 'USA',
  },
  {
    name: 'Azure',
    domains: ['microsoft.com', 'azure.com'],
    senderPatterns: [/azure.*@.*\.com/i, /noreply@microsoft\.com/i],
    subjectPatterns: [/azure.*code/i, /verification.*azure/i, /microsoft.*azure.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/azure\.microsoft\.com.*\/verify/i],
    commonPhrases: ['Azure verification code', 'Your code', 'Microsoft Azure code'],
    confidence: 98,
    industry: 'Cloud Services',
    country: 'USA',
  },
  {
    name: 'Heroku',
    domains: ['heroku.com'],
    senderPatterns: [/heroku.*@.*\.com/i, /noreply@heroku\.com/i],
    subjectPatterns: [/heroku.*code/i, /verification.*heroku/i, /heroku.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/heroku\.com.*\/verify/i],
    commonPhrases: ['Heroku verification code', 'Your code', 'Heroku code'],
    confidence: 95,
    industry: 'Cloud Services',
    country: 'USA',
  },
  {
    name: 'DigitalOcean',
    domains: ['digitalocean.com'],
    senderPatterns: [/digitalocean.*@.*\.com/i, /noreply@digitalocean\.com/i],
    subjectPatterns: [/digitalocean.*code/i, /verification.*digitalocean/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/digitalocean\.com.*\/verify/i],
    commonPhrases: ['DigitalOcean verification code', 'Your code', 'DO code'],
    confidence: 95,
    industry: 'Cloud Services',
    country: 'USA',
  },
  {
    name: 'Cloudflare',
    domains: ['cloudflare.com'],
    senderPatterns: [/cloudflare.*@.*\.com/i, /noreply@cloudflare\.com/i],
    subjectPatterns: [/cloudflare.*code/i, /verification.*cloudflare/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/cloudflare\.com.*\/verify/i],
    commonPhrases: ['Cloudflare verification code', 'Your code', 'Cloudflare code'],
    confidence: 95,
    industry: 'Cloud Services',
    country: 'USA',
  },

  // ────────────────────────────────────────────────────────────
  //  INDIAN SERVICES & STARTUPS
  // ────────────────────────────────────────────────────────────
  {
    name: 'Flipkart',
    domains: ['flipkart.com'],
    senderPatterns: [/flipkart.*@.*\.com/i, /noreply@flipkart\.com/i],
    subjectPatterns: [/flipkart.*code/i, /verification.*flipkart/i, /flipkart.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/flipkart\.com.*\/verify/i],
    commonPhrases: ['Flipkart verification code', 'Your code', 'Flipkart code'],
    confidence: 95,
    industry: 'E-commerce',
    country: 'India',
  },
  {
    name: 'Paytm',
    domains: ['paytm.com', 'one97.com'],
    senderPatterns: [/paytm.*@.*\.com/i, /noreply@paytm\.com/i],
    subjectPatterns: [/paytm.*code/i, /verification.*paytm/i, /paytm.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/paytm\.com.*\/verify/i],
    commonPhrases: ['Paytm verification code', 'Your code', 'Paytm code'],
    confidence: 95,
    industry: 'Financial',
    country: 'India',
  },
  {
    name: 'PhonePe',
    domains: ['phonepe.com'],
    senderPatterns: [/phonepe.*@.*\.com/i, /noreply@phonepe\.com/i],
    subjectPatterns: [/phonepe.*code/i, /verification.*phonepe/i, /phonepe.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/phonepe\.com.*\/verify/i],
    commonPhrases: ['PhonePe verification code', 'Your code', 'PhonePe code'],
    confidence: 95,
    industry: 'Financial',
    country: 'India',
  },
  {
    name: 'Google Pay India',
    domains: ['google.com', 'tez.google.com'],
    senderPatterns: [/googlepay.*@.*\.com/i, /noreply@google\.com/i],
    subjectPatterns: [/google.*pay.*code/i, /verification.*google.*pay/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/pay\.google\.com.*\/verify/i],
    commonPhrases: ['Google Pay verification code', 'Your code', 'GPay code'],
    confidence: 95,
    industry: 'Financial',
    country: 'India',
  },
  {
    name: 'Zomato',
    domains: ['zomato.com'],
    senderPatterns: [/zomato.*@.*\.com/i, /noreply@zomato\.com/i],
    subjectPatterns: [/zomato.*code/i, /verification.*zomato/i, /zomato.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/zomato\.com.*\/verify/i],
    commonPhrases: ['Zomato verification code', 'Your code', 'Zomato code'],
    confidence: 95,
    industry: 'Food Delivery',
    country: 'India',
  },
  {
    name: 'Swiggy',
    domains: ['swiggy.com'],
    senderPatterns: [/swiggy.*@.*\.com/i, /noreply@swiggy\.com/i],
    subjectPatterns: [/swiggy.*code/i, /verification.*swiggy/i, /swiggy.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/swiggy\.com.*\/verify/i],
    commonPhrases: ['Swiggy verification code', 'Your code', 'Swiggy code'],
    confidence: 95,
    industry: 'Food Delivery',
    country: 'India',
  },
  {
    name: 'Ola',
    domains: ['olacabs.com', 'ola.com'],
    senderPatterns: [/ola.*@.*\.com/i, /noreply@olacabs\.com/i],
    subjectPatterns: [/ola.*code/i, /verification.*ola/i, /ola.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/olacabs\.com.*\/verify/i],
    commonPhrases: ['Ola verification code', 'Your code', 'Ola code'],
    confidence: 95,
    industry: 'Transportation',
    country: 'India',
  },
  {
    name: 'OYO',
    domains: ['oyorooms.com', 'oyo.com'],
    senderPatterns: [/oyo.*@.*\.com/i, /noreply@oyorooms\.com/i],
    subjectPatterns: [/oyo.*code/i, /verification.*oyo/i, /oyo.*verification/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/oyorooms\.com.*\/verify/i],
    commonPhrases: ['OYO verification code', 'Your code', 'OYO code'],
    confidence: 95,
    industry: 'Hospitality',
    country: 'India',
  },
  {
    name: 'MakeMyTrip',
    domains: ['makemytrip.com'],
    senderPatterns: [/makemytrip.*@.*\.com/i, /noreply@makemytrip\.com/i],
    subjectPatterns: [/makemytrip.*code/i, /verification.*makemytrip/i],
    emailIntent: 'verification',
    otpLength: 6,
    otpFormat: 'numeric',
    linkPatterns: [/makemytrip\.com.*\/verify/i],
    commonPhrases: ['MakeMyTrip verification code', 'Your code', 'MMT code'],
    confidence: 95,
    industry: 'Travel',
    country: 'India',
  },
];
