#!/usr/bin/env python3
"""Generate the small, shape-matched displacement maps used by GhostFill glass.

Run this script after changing a control's dominant aspect ratio or corner radius.
The center stays neutral; only the rounded rim bends the backdrop.

Technique adapted from Leonard van Hemert's MIT-licensed liquid-glass-react:
https://github.com/LeonardSEO/liquid-glass-react
Edge falloff informed by Sebastian Degenaar's MIT-licensed lightweight shader:
https://github.com/sdegenaar/liquid_glass_widgets
Licenses are retained in docs/third-party.
"""

from base64 import b64encode
from math import hypot
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "public" / "assets"
RASTER_SCALE = 3  # Preserve smooth rim gradients at common high-DPI display scales.
# ponytail: fixed maps fit the dominant control sizes; regenerate when geometry changes.
SHAPES = {
    "glass-lens-pill.png": (168, 36, 18, 7),
    "glass-lens-control.png": (142, 44, 12, 8),
    "glass-lens-wide.png": (240, 44, 12, 8),
    "glass-lens-icon.png": (34, 34, 11, 6),
    "glass-lens-fab.png": (44, 44, 16, 8),
}


def signed_distance(x: float, y: float, width: int, height: int, radius: int) -> float:
    dx = abs(x - width / 2) - (width / 2 - radius)
    dy = abs(y - height / 2) - (height / 2 - radius)
    return hypot(max(dx, 0), max(dy, 0)) + min(max(dx, dy), 0) - radius


def make_map(width: int, height: int, radius: int, rim: int) -> Image.Image:
    image = Image.new("RGBA", (width * RASTER_SCALE, height * RASTER_SCALE))
    pixels = image.load()

    for y in range(image.height):
        for x in range(image.width):
            px, py = (x + 0.5) / RASTER_SCALE, (y + 0.5) / RASTER_SCALE
            distance = signed_distance(px, py, width, height, radius)
            dx = signed_distance(px + 1, py, width, height, radius) - signed_distance(
                px - 1, py, width, height, radius
            )
            dy = signed_distance(px, py + 1, width, height, radius) - signed_distance(
                px, py - 1, width, height, radius
            )
            length = hypot(dx, dy) or 1
            t = min(max(-distance / rim, 0), 1)
            # Quadratic edge influence follows liquid_glass_widgets' curved
            # meniscus: a pronounced rim with an undistorted flat interior.
            falloff = (1 - t * t * (3 - 2 * t)) ** 2
            red = round(min(max(128 + (dx / length) * falloff * 127, 0), 255))
            green = round(min(max(128 + (dy / length) * falloff * 127, 0), 255))
            pixels[x, y] = (red, green, 128, 255)

    return image


def main() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for name, shape in SHAPES.items():
        target = OUTPUT / name
        image = make_map(*shape)
        width, height = image.size
        assert image.size == (shape[0] * RASTER_SCALE, shape[1] * RASTER_SCALE)
        # One runnable optics check: flat center, outward normals, opaque map.
        assert image.getpixel((width // 2, height // 2)) == (128, 128, 128, 255)
        assert image.getpixel((0, height // 2))[0] < 32
        assert image.getpixel((width - 1, height // 2))[0] > 224
        assert image.getpixel((width // 2, 0))[1] < 32
        assert image.getpixel((width // 2, height - 1))[1] > 224
        assert image.getextrema()[3] == (255, 255)
        image.save(target, optimize=True)
        print(f"{target.relative_to(ROOT)} ({target.stat().st_size} bytes)")

    # The content script's closed Shadow DOM cannot depend on page-relative
    # asset URLs. Inline this one tiny map without adding web-accessible
    # extension resources or network requests to the host page.
    icon = OUTPUT / "glass-lens-fab.png"
    data_uri = "data:image/png;base64," + b64encode(icon.read_bytes()).decode("ascii")
    module = ROOT / "src" / "content" / "glassLensMap.ts"
    module.write_text(
        "// Generated by scripts/generate-glass-lenses.py. Do not edit by hand.\n"
        f"export const glassIconMap = '{data_uri}';\n",
        encoding="utf-8",
    )
    print(module.relative_to(ROOT))


if __name__ == "__main__":
    main()
